id: "move"
name: "Move"
description: "Move files"
inputs:
  source:
    description: "File to move (glob)"
    required: true
  destination:
    description: "Destination to move to"
    required: true
  force:
    description: "Force the move (overwrite)"
    type: boolean
    default: true
  allow-outside-working-directory:
    description: "Allow destination/matched files to be outside the working directory"
    type: boolean
    default: false
outputs:
  paths:
    description: The new paths
    type: array
    items: string
runs:
  using: "python"
  main: "move/main.py"